## Download fastq files for Rep1 and Rep2 for ESC, DE, PGT, PP, and BETA.
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE210524 <br>
https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA866097&o=acc_s%3Aa <br>
/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC <br>

In [1]:
# Create a conda env for sra-tools
# conda create -n sra-tools -c bioconda sra-tools

In [1]:
data_dir='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/fastq'
conditions=['ESC_R1','ESC_R2','DE_R1','DE_R2','PGT_R1','PGT_R2','PP_R1','PP_R2','BETA_R1','BETA_R2']
SRA_runs={
    'ESC_R1': 'SRR20825718',
    'ESC_R2': 'SRR21023366',
    'DE_R1': 'SRR20825716',
    'DE_R2': 'SRR20825715',
    'PGT_R1': 'SRR20825722',
    'PGT_R2': 'SRR20825721',
    'PP_R1': 'SRR20825720',
    'PP_R2': 'SRR20825719',
    'BETA_R1': 'SRR20825714',
    'BETA_R2': 'SRR20825713'
}

In [2]:
# for cond in conditions:
#     SRA_run=SRA_runs[cond]

#     !bsub -q "long" -W 20:00 \
#         -e /home/jiangyuan.liu5-umw/projects/4DNII/lsf_jobs/LSB_%J.err \
#         -o /home/jiangyuan.liu5-umw/projects/4DNII/lsf_jobs/LSB_%J.log \
#         -n 1 -R "rusage[mem=64G]" \
#         -N -u jiangyuan.liu5@umassmed.edu \
#         "source ~/.bashrc && conda activate sra-tools && fastq-dump --gzip --outdir $data_dir --split-3 $SRA_run"

Job <885099> is submitted to queue <long>.
Job <885100> is submitted to queue <long>.
Job <885101> is submitted to queue <long>.
Job <885102> is submitted to queue <long>.
Job <885103> is submitted to queue <long>.
Job <885104> is submitted to queue <long>.
Job <885105> is submitted to queue <long>.
Job <885106> is submitted to queue <long>.
Job <885107> is submitted to queue <long>.
Job <885108> is submitted to queue <long>.

## Generate mcool files using distiller

### Create a yml file as input for distiller pipeline

In [2]:
import yaml

In [3]:
fastq_dir='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/fastq/'
raw_reads_paths={}
for cond in conditions:
    raw_reads_paths[cond+'__hg38']={'lane1':[fastq_dir+SRA_runs[cond]+'_1.fastq.gz',fastq_dir+SRA_runs[cond]+'_2.fastq.gz']}

In [4]:
library_groups={
    'ESC_R1R2': ['ESC_R1__hg38', 'ESC_R2__hg38'],
    'DE_R1R2': ['DE_R1__hg38', 'DE_R2__hg38'],
    'PGT_R1R2': ['PGT_R1__hg38', 'PGT_R2__hg38'],
    'PP_R1R2': ['PP_R1__hg38', 'PP_R2__hg38'],
    'BETA_R1R2': ['BETA_R1__hg38', 'BETA_R2__hg38'],
    'MEGA': ['ESC_R1__hg38', 'ESC_R2__hg38', 'DE_R1__hg38', 'DE_R2__hg38', 'PGT_R1__hg38', 'PGT_R2__hg38', 'PP_R1__hg38', 'PP_R2__hg38', 'BETA_R1__hg38', 'BETA_R2__hg38']
}

In [5]:
# # Generated a distiller project yml file template from clims
# with open('/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/distiller-project.yml', 'r') as read_file:
#     contents=yaml.safe_load(read_file)
#     # Need to replace:
#     # contents['input']['raw_reads_paths']
#     # contents['input']['library_groups']
#     contents['input']['raw_reads_paths']=raw_reads_paths
#     contents['input']['library_groups']=library_groups

# with open('/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/Lyu_et_al_2023.yml', 'w') as dump_file:
#     yaml.dump(contents, dump_file, sort_keys=False)

In [ ]:
# Run distiller
# cd /home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/coolers
# bsub < run.sh

### Check number of reads and cis and trans ratios

In [1]:
import pandas as pd
import numpy as np

In [2]:
stats_dir='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/coolers/results/stats_library_group/'
conditions=['ESC_R1R2','DE_R1R2','PGT_R1R2','PP_R1R2','BETA_R1R2','MEGA']

total_nodups=[]
cis=[]
trans=[]
for cond in conditions:
    filename=f'{stats_dir}{cond}.hg38.stats'
    df=pd.read_csv(filename, sep='\t', header=None)
    total_nodups.append(list(df.loc[df[0] == 'total_nodups',1])[0])
    cis.append(list(df.loc[df[0] == 'cis',1])[0])
    trans.append(list(df.loc[df[0] == 'trans',1])[0])

In [3]:
summary_df=pd.DataFrame(np.array([conditions, total_nodups, cis, trans]).T, columns=['condition', 'total_nodups', 'cis', 'trans'])
summary_df=summary_df.astype({'total_nodups': 'int64', 'cis': 'int64', 'trans': 'int64'})
summary_df['cis_percent']=round(summary_df.cis/summary_df.total_nodups, 2)
summary_df['trans_percent']=round(summary_df.trans/summary_df.total_nodups, 2)

In [4]:
summary_df

   condition  total_nodups         cis      trans  cis_percent  trans_percent
0   ESC_R1R2     924375815   813546032  110829783         0.88           0.12
1    DE_R1R2     821977930   704414493  117563437         0.86           0.14
2   PGT_R1R2     803952371   663244806  140707565         0.82           0.18
3    PP_R1R2     771559587   676857684   94701903         0.88           0.12
4  BETA_R1R2    1011491711   889528186  121963525         0.88           0.12
5       MEGA    4333357414  3747591201  585766213         0.86           0.14

## Old method: Generate a union list of loops by overlapping loops called from each individual libraries at 5kb resolution

### Call loops at 5kb resolution for each individual library (used for later comparison with my optimized method)

In [21]:
import pandas as pd

In [22]:
clr_dir='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/coolers/results/coolers_library_group/'

coolers = {'name': ['ESC_R1R2',
                    'DE_R1R2',
                    'PGT_R1R2',
                    'PP_R1R2',
                    'BETA_R1R2',
                    'MEGA'],
           'path': [clr_dir+'ESC_R1R2.hg38.mapq_30.1000.mcool',
                    clr_dir+'DE_R1R2.hg38.mapq_30.1000.mcool',
                    clr_dir+'PGT_R1R2.hg38.mapq_30.1000.mcool',
                    clr_dir+'PP_R1R2.hg38.mapq_30.1000.mcool',
                    clr_dir+'BETA_R1R2.hg38.mapq_30.1000.mcool',
                    clr_dir+'MEGA.hg38.mapq_30.1000.mcool'
                   ]} 
coolers = pd.DataFrame.from_dict(coolers)

# coolers.to_csv('/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/cooler_paths_of_Lyu_et_al_2023.tsv', sep='\t', index=False, header=True)

In [24]:
input_coolers='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/cooler_paths_of_Lyu_et_al_2023.tsv'
output_folder='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_5kb_old'

# !bsub -q "long" -W 32:00 \
#     -e /home/jiangyuan.liu5-umw/projects/4DNII/lsf_jobs/LSB_%J.err \
#     -o /home/jiangyuan.liu5-umw/projects/4DNII/lsf_jobs/LSB_%J.log \
#     -n 8 -R "rusage[mem=8000]" \
#     -N -u jiangyuan.liu5@umassmed.edu \
#     "python /home/jiangyuan.liu5-umw/projects/4DNII/notebooks/dots_R1R2_updated/scripts/Generate_dots_from_each_individual_libraries.py $input_coolers $output_folder"

INFO: Total memory requested is 64000 MB (8 cores x 8000 MB)
Job <903676> is submitted to queue <long>.

### Merge loops called from each individual library

In [1]:
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
dots_dir='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_5kb_old/'
dots_meta=pd.read_csv(dots_dir+'dots_meta_5kb.tsv', sep='\t')

In [3]:
dots_meta

        name                                               path
0   ESC_R1R2  /home/jiangyuan.liu5-umw/projects/4DNII/public...
1    DE_R1R2  /home/jiangyuan.liu5-umw/projects/4DNII/public...
2   PGT_R1R2  /home/jiangyuan.liu5-umw/projects/4DNII/public...
3    PP_R1R2  /home/jiangyuan.liu5-umw/projects/4DNII/public...
4  BETA_R1R2  /home/jiangyuan.liu5-umw/projects/4DNII/public...
5       MEGA  /home/jiangyuan.liu5-umw/projects/4DNII/public...

In [4]:
dots_list=[]
for i in range(len(dots_meta)):
    df=pd.read_csv(dots_meta.path[i], sep='\t')[['chrom1','start1','end1','chrom2','start2','end2']]
    df['sample_name']=dots_meta.name[i]
    dots_list.append(df)
dots=pd.concat(dots_list)

In [5]:
import bioframe
import pandas as pd
import numpy as np

def merge_dots(df):
    overlapped_anchors_left=bioframe.cluster(df[['chrom1','start1','end1']].copy().rename(columns={'chrom1': 'chrom', 'start1': 'start', 'end1': 'end'}), min_dist=None)
    overlapped_anchors_right=bioframe.cluster(df[['chrom2','start2','end2','sample_name']].copy().rename(columns={'chrom2': 'chrom', 'start2': 'start', 'end2': 'end'}), min_dist=None)
    overlapped_dots=pd.merge(overlapped_anchors_left, overlapped_anchors_right, left_index=True, right_index=True, suffixes=(1,2))
    sample_name=overlapped_dots.groupby(['cluster1','cluster2'])['sample_name'].apply(lambda x: '&'.join(list(np.unique(x)))).reset_index()
    overlapped_dots=pd.merge(overlapped_dots[['cluster1','cluster2','chrom1','cluster_start1','cluster_end1','chrom2','cluster_start2','cluster_end2']], sample_name, on=['cluster1','cluster2'])
    overlapped_dots=overlapped_dots.drop(['cluster1', 'cluster2'], axis=1).rename(columns={'cluster_start1': 'start1', 'cluster_end1': 'end1', 'cluster_start2': 'start2', 'cluster_end2': 'end2'})
    overlapped_dots=overlapped_dots.drop_duplicates().reset_index(drop=True)
    return overlapped_dots

In [6]:
merged_dots=merge_dots(dots)

In [7]:
len(merged_dots) # Total 21051 loops

21051

In [8]:
# For testing purpose
# Since all anchors are same resolution, we can simplify merge_dots() with below two lines in the future
df=dots.reset_index(drop=True).copy()
a=df.groupby(['chrom1','start1','end1','chrom2','start2','end2'])['sample_name'].apply(lambda x: '&'.join(list(np.unique(x)))).reset_index()

are_equal = merged_dots.sort_values(by=merged_dots.columns.tolist()).reset_index(drop=True).equals(
    a.sort_values(by=a.columns.tolist()).reset_index(drop=True)
)
print("DataFrames are equal (ignoring row order):", are_equal)

DataFrames are equal (ignoring row order): True

In [9]:
merged_dots

      chrom1    start1      end1 chrom2    start2      end2    sample_name
0      chr10  24215000  24220000  chr10  24360000  24365000  ESC_R1R2&MEGA
1      chr10  21280000  21285000  chr10  21515000  21520000       ESC_R1R2
2      chr10  30390000  30395000  chr10  30590000  30595000       ESC_R1R2
3      chr10  26740000  26745000  chr10  26870000  26875000       ESC_R1R2
4      chr10  22250000  22255000  chr10  22320000  22325000  ESC_R1R2&MEGA
...      ...       ...       ...    ...       ...       ...            ...
21046   chrX  69540000  69545000   chrX  69620000  69625000           MEGA
21047   chrX  68825000  68830000   chrX  69390000  69395000           MEGA
21048   chrX  71390000  71395000   chrX  71555000  71560000           MEGA
21049   chrX  68825000  68830000   chrX  68980000  68985000           MEGA
21050   chrX  65030000  65035000   chrX  65525000  65530000           MEGA

[21051 rows x 7 columns]

In [10]:
# merged_dots.to_csv(dots_dir+'union_dot_list_of_Lyu_et_al_2023_5kb_old_method.txt', sep='\t', index=False, header=True)

### Generate clusters of enriched pixels for each individual library

In [1]:
input_coolers='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/cooler_paths_of_Lyu_et_al_2023.tsv'
output_folder='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_5kb_old/clusters'

# !bsub -q "long" -W 32:00 \
#     -e /home/jiangyuan.liu5-umw/projects/4DNII/lsf_jobs/LSB_%J.err \
#     -o /home/jiangyuan.liu5-umw/projects/4DNII/lsf_jobs/LSB_%J.log \
#     -n 8 -R "rusage[mem=8000]" \
#     -N -u jiangyuan.liu5@umassmed.edu \
#     "python /home/jiangyuan.liu5-umw/projects/4DNII/notebooks/dots_R1R2_updated/scripts/generate_clusters_of_enriched_pixels.py $input_coolers $output_folder"

INFO: Total memory requested is 64000 MB (8 cores x 8000 MB)
Job <826169> is submitted to queue <long>.

### Generate centroids of clusters for each individual library (i.e., cluster_filtering=False in dots())

In [2]:
input_coolers='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/cooler_paths_of_Lyu_et_al_2023.tsv'
output_folder='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_5kb_old/centroids'

# !bsub -q "long" -W 32:00 \
#     -e /home/jiangyuan.liu5-umw/projects/4DNII/lsf_jobs/LSB_%J.err \
#     -o /home/jiangyuan.liu5-umw/projects/4DNII/lsf_jobs/LSB_%J.log \
#     -n 8 -R "rusage[mem=8000]" \
#     -N -u jiangyuan.liu5@umassmed.edu \
#     "python /home/jiangyuan.liu5-umw/projects/4DNII/notebooks/dots_R1R2_updated/scripts/Generate_dots_from_each_individual_libraries_no_HiCCUPS_filtering.py $input_coolers $output_folder"

INFO: Total memory requested is 64000 MB (8 cores x 8000 MB)
Job <826170> is submitted to queue <long>.

### Annotate centroid dataframe with columns, including removed (bool), c_start1, c_end1, c_start2, c_end2 (for its cluster)

In [1]:
import pandas as pd
import numpy as np

In [2]:
clusters_meta='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_5kb_old/clusters/clusters_meta_5kb.tsv'
centroids_meta='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_5kb_old/centroids/dots_meta_5kb_no_HiCCUPS_filtering.tsv'
loops_meta='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_5kb_old/dots_meta_5kb.tsv'

clusters_meta=pd.read_csv(clusters_meta, sep='\t').set_index('name')['path'].to_dict()
centroids_meta=pd.read_csv(centroids_meta, sep='\t').set_index('name')['path'].to_dict()
loops_meta=pd.read_csv(loops_meta, sep='\t').set_index('name')['path'].to_dict()

In [3]:
import pandas as pd
import numpy as np

def annotate_centroid_df(clusters, centroids, loops):
    clusters=pd.read_csv(clusters,sep='\t')[['chrom1','start1','end1','chrom2','start2','end2','region','c_label','c_size']]
    centroids=pd.read_csv(centroids,sep='\t')[['chrom1','start1','end1','chrom2','start2','end2','region','c_label','c_size']]
    loops=pd.read_csv(loops,sep='\t')[['chrom1','start1','end1','chrom2','start2','end2','region','c_label','c_size']]

    clusters=clusters.groupby(['region', 'c_label']).agg(
        c_start1=('start1', 'min'),
        c_end1=('end1', 'max'),
        c_start2=('start2', 'min'),
        c_end2=('end2', 'max')
    ).reset_index()

    centroids=pd.merge(centroids, clusters, on=['region','c_label'])

    centroids_annotated=pd.merge(centroids, loops, on=['region','c_label'], how='left', indicator=True, suffixes=('', '_loop'))
    centroids_annotated['removed']=False
    centroids_annotated.loc[centroids_annotated._merge == 'left_only', 'removed']=True
    centroids_annotated=centroids_annotated[list(centroids.columns)+['removed']]
    centroids_annotated['centroid_ID']=list(centroids_annotated.index)
    
    return centroids_annotated

In [4]:
conditions=['ESC_R1R2',
            'DE_R1R2',
            'PGT_R1R2',
            'PP_R1R2',
            'BETA_R1R2']

annotated_centroids={}
for cond in conditions:
    annotated_centroids[cond]=annotate_centroid_df(clusters_meta[cond], centroids_meta[cond], loops_meta[cond])

In [6]:
# centroid_dir='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_5kb_old/centroids/'
# for cond in conditions:
#     annotated_centroids[cond].to_csv(centroid_dir+f'{cond}.hg38.mapq_30.5kb.dots.no.HiCCUPS.filtering.annotated.tsv', sep='\t', index=False, header=True)

In [6]:
# centroid_dir='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_5kb_old/centroids/'
# annotate_centroid_df(clusters_meta['MEGA'], centroids_meta['MEGA'], loops_meta['MEGA']).to_csv(centroid_dir+'MEGA.hg38.mapq_30.5kb.dots.no.HiCCUPS.filtering.annotated.tsv', sep='\t', index=False, header=True)

In [5]:
annotated_centroids['ESC_R1R2']

,chrom1,start1,end1,chrom2,start2,end2,region,c_label,c_size,c_start1,c_end1,c_start2,c_end2,removed,centroid_ID
0,chr10,24215000,24220000,chr10,24360000,24365000,chr10_p,0,1,24215000,24220000,24360000,24365000,False,0
1,chr10,21280000,21285000,chr10,21515000,21520000,chr10_p,1,2,21275000,21285000,21490000,21520000,False,1
2,chr10,23155000,23160000,chr10,23290000,23295000,chr10_p,2,1,23155000,23160000,23290000,23295000,True,2
3,chr10,35235000,35240000,chr10,35555000,35560000,chr10_p,3,1,35235000,35240000,35555000,35560000,True,3
4,chr10,30390000,30395000,chr10,30590000,30595000,chr10_p,4,2,30390000,30395000,30580000,30595000,False,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4755,chrX,137570000,137575000,chrX,137920000,137925000,chrX_q,44,1,137570000,137575000,137920000,137925000,True,4755
4756,chrX,111445000,111450000,chrX,111680000,111685000,chrX_q,45,1,111445000,111450000,111680000,111685000,True,4756
4757,chrX,68185000,68190000,chrX,68710000,68715000,chrX_q,46,1,68185000,68190000,68710000,68715000,True,4757
4758,chrX,97955000,97960000,chrX,98350000,98355000,chrX_q,47,1,97955000,97960000,98350000,98355000,True,4758
4759,chrX,94620000,94625000,chrX,94770000,94775000,chrX_q,48,1,94620000,94625000,94770000,94775000,True,4759

## New method: Generate a union list of loops using my nextflow pipeline at 5kb resolution

In [ ]:
# Run my pipeline
# cd /home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_5kb_new
# bsub < run.sh

## Old method: Generate a union list of loops by overlapping loops called from each individual libraries at 10kb resolution

### Call loops at 10kb resolution for each individual library (used for later comparison with my optimized method)

In [37]:
input_coolers='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/cooler_paths_of_Lyu_et_al_2023.tsv'
output_folder='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_10kb_old'
resolution=10000

# !bsub -q "long" -W 32:00 \
#     -e /home/jiangyuan.liu5-umw/projects/4DNII/lsf_jobs/LSB_%J.err \
#     -o /home/jiangyuan.liu5-umw/projects/4DNII/lsf_jobs/LSB_%J.log \
#     -n 8 -R "rusage[mem=8000]" \
#     -N -u jiangyuan.liu5@umassmed.edu \
#     "python /home/jiangyuan.liu5-umw/projects/4DNII/notebooks/dots_R1R2_updated/scripts/Generate_dots_from_each_individual_libraries_with_different_resolutions.py $input_coolers $output_folder $resolution"

INFO: Total memory requested is 64000 MB (8 cores x 8000 MB)
Job <907219> is submitted to queue <long>.

### Merge loops called from each individual library

In [1]:
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
dots_dir='/home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_10kb_old/'
dots_meta=pd.read_csv(dots_dir+'dots_meta_10kb.tsv', sep='\t')
dots_meta

        name                                               path
0   ESC_R1R2  /home/jiangyuan.liu5-umw/projects/4DNII/public...
1    DE_R1R2  /home/jiangyuan.liu5-umw/projects/4DNII/public...
2   PGT_R1R2  /home/jiangyuan.liu5-umw/projects/4DNII/public...
3    PP_R1R2  /home/jiangyuan.liu5-umw/projects/4DNII/public...
4  BETA_R1R2  /home/jiangyuan.liu5-umw/projects/4DNII/public...
5       MEGA  /home/jiangyuan.liu5-umw/projects/4DNII/public...

In [3]:
dots_list=[]
for i in range(len(dots_meta)):
    df=pd.read_csv(dots_meta.path[i], sep='\t')[['chrom1','start1','end1','chrom2','start2','end2']]
    df['sample_name']=dots_meta.name[i]
    dots_list.append(df)
dots=pd.concat(dots_list)

In [4]:
import bioframe
import pandas as pd
import numpy as np

def merge_dots(df):
    overlapped_anchors_left=bioframe.cluster(df[['chrom1','start1','end1']].copy().rename(columns={'chrom1': 'chrom', 'start1': 'start', 'end1': 'end'}), min_dist=None)
    overlapped_anchors_right=bioframe.cluster(df[['chrom2','start2','end2','sample_name']].copy().rename(columns={'chrom2': 'chrom', 'start2': 'start', 'end2': 'end'}), min_dist=None)
    overlapped_dots=pd.merge(overlapped_anchors_left, overlapped_anchors_right, left_index=True, right_index=True, suffixes=(1,2))
    sample_name=overlapped_dots.groupby(['cluster1','cluster2'])['sample_name'].apply(lambda x: '&'.join(list(np.unique(x)))).reset_index()
    overlapped_dots=pd.merge(overlapped_dots[['cluster1','cluster2','chrom1','cluster_start1','cluster_end1','chrom2','cluster_start2','cluster_end2']], sample_name, on=['cluster1','cluster2'])
    overlapped_dots=overlapped_dots.drop(['cluster1', 'cluster2'], axis=1).rename(columns={'cluster_start1': 'start1', 'cluster_end1': 'end1', 'cluster_start2': 'start2', 'cluster_end2': 'end2'})
    overlapped_dots=overlapped_dots.drop_duplicates().reset_index(drop=True)
    return overlapped_dots

In [5]:
merged_dots=merge_dots(dots)

In [6]:
len(merged_dots) # Total 30621 loops

30621

In [7]:
merged_dots

,chrom1,start1,end1,chrom2,start2,end2,sample_name
0,chr10,5450000,5460000,chr10,5590000,5600000,ESC_R1R2
1,chr10,6670000,6680000,chr10,7420000,7430000,ESC_R1R2
2,chr10,8040000,8050000,chr10,8320000,8330000,ESC_R1R2
3,chr10,7520000,7530000,chr10,7680000,7690000,BETA_R1R2&ESC_R1R2&MEGA&PP_R1R2
4,chr10,6420000,6430000,chr10,6650000,6660000,ESC_R1R2
...,...,...,...,...,...,...,...
30616,chrX,107790000,107800000,chrX,108060000,108070000,MEGA
30617,chrX,107540000,107550000,chrX,107890000,107900000,MEGA
30618,chrX,105190000,105200000,chrX,105700000,105710000,MEGA
30619,chrX,108300000,108310000,chrX,108530000,108540000,MEGA
30620,chrX,107020000,107030000,chrX,107630000,107640000,MEGA

In [9]:
# merged_dots.to_csv(dots_dir+'union_dot_list_of_Lyu_et_al_2023_10kb_old_method.txt', sep='\t', index=False, header=True)

## New method: Generate a union list of loops using my nextflow pipeline at 10kb resolution

In [ ]:
# Run my pipeline
# cd /home/jiangyuan.liu5-umw/projects/4DNII/public_data_verification_for_union_list_loop_caller/public_datasets/Lyu_et_al_2023/In_situ_HiC/unionloops_10kb_new
# bsub < run.sh